// src/renderer/components/Editor.vue
<script setup lang="ts">
type Props = {
  modelValue: string | undefined
}
type Emits = {
  (e: 'create-clicked'): void
  (e: 'update:modelValue', v: string | undefined): void
}
const props = defineProps<Props>()
const emit = defineEmits<Emits>()
</script>

<template>
  <div class="editor-layout">
    <textarea
      type="text"
      placeholder="メモを入力"
      class="note-input"
      :value="props.modelValue"
      @input="(e: any) => emit('update:modelValue', e.target.value)"
    />
    <button
      type="button"
      class="create-button"
      @click="() => emit('create-clicked')"
    >
      追加
    </button>
  </div>
</template>

<style scoped>
.editor-layout {
  display: grid;
  grid-template-columns: 1fr auto;
}

.note-input {
  grid-column: 1/2;
}

.create-button {
  grid-column: 2/3;
}
</style>

// src/renderer-react/src/components/Editor.tsx
type EditorProps = {
  text: string
  onTextChange: (text: string) => void
  onCreateClicked: () => void
}

export default function Editor({
  text,
  onTextChange,
  onCreateClicked,
}: EditorProps) {
  return (
    <div className="grid grid-cols-[1fr_auto]">
      <textarea
        className="resize-none"
        itemType="text"
        placeholder="メモを入力"
        value={text}
        onChange={(e) => onTextChange(e.target.value)}
      />
      <button type="button" onClick={onCreateClicked}>
        追加
      </button>
    </div>
  )
}
